version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: channel_key
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key